# Generated by Django 3.1.2 on 2021-08-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'foods'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name_plural': 'notifies'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
