# Generated by Django 3.1.2 on 2021-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210816_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
