# Generated by Django 3.1.2 on 2021-08-23 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210820_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
