# Generated by Django 3.1.2 on 2021-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210907_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_saved',
            field=models.ManyToManyField(blank=True, to='main.Food'),
        ),
    ]
